routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UserController@index')->name('home');
Route::get('/user/{user}/calls', 'UserController@calls' )->name('user.calls');
Route::resource('calls', 'CallController',['except' => 'create']);
Route::get('user/{user_id}/calls/create',['as' => 'calls.create', 'uses' => 'CallController@create']);

app/Call.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Call extends Model
{
    const STATUS_ACTIVE = 'active';
    const STATUS_DISABLED = 'disabled';

    protected $fillable = ['user_id','description'];

    /**
     * Get the user that owns the comment.
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }
    /**
     * The model's default values for attributes.
     *
     * @var array
     */
    protected $attributes = [
        'status' => self::STATUS_ACTIVE,
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function calls(){
        return $this->hasMany('App\Call');
    }
}

app/Http/Controllers/CallController.php
<?php

namespace App\Http\Controllers;

use App\Call;
use App\Http\Requests\StoreCall;
use Illuminate\Http\Request;

class CallController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $calls = Call::with('user')->paginate(15);
        return view('calls.index_calls', compact('calls'));
    }

    /**
     * Show the form for creating a new resource.
     * @param $user_id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create($user_id)
    {
        return view('calls.create_call', compact('user_id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCall $request)
    {
        $call = new Call();
        $call->fill($request->all());
        try{
            $call->save();
            return redirect()->route('user.calls',['user' => $call->user_id]);
        }catch(\Exception $e){
            return back()->withError($e->getMessage())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Call $call)
    {
        try{
            $call->delete();
            return back();
        }catch(\Exception $e){
            return back()->withError($e->getMessage())->withInput();
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(10);
        return view('users', compact('users'));
    }


    /**
     * @param User $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function calls(User $user){
        $calls = $user->calls()->paginate(3);
        return view('user_calls', compact('calls','user'));

    }
}

resources/views/calls.blade.php
@extends('layout')
@section('content')
  @foreach($calls as $call)
    <p>{{$call->id}}</p>
  @endforeach
@endsection

resources/views/calls/create_call.blade.php
@extends('layout')
@section('content')
  <div class="container">
    <div class="d-flex flex-column">
      <h1>Create new call</h1>
      @if(!empty($errors->first()))
        <div class="d-flex flex-column">
          <div class="alert alert-danger">
            <span>{{ $errors->first() }}</span>
          </div>
        </div>
      @endif
      @if (session('error'))
        <div class="d-flex flex-column">
          <div class="alert alert-danger">{{ session('error') }}</div>
        </div>
      @endif
      {!! Form::open(['url'=>route('calls.store'), 'class'=>'form-horizontal','method' => 'POST']) !!}
      <div class="form-group">
        {!! Form::label('description', 'Your text', array('class' => 'awesome')) !!}
        {!! Form::textarea('description', '',[ 'class' => 'form-control']) !!}
      </div>
      {!! Form::hidden('user_id', $user_id) !!}
      <div class="form-group">
        {!! Form::submit('Save',['class' => 'btn btn-primary']) !!}
        {!! Form::close() !!}
      </div>
    </div>
  </div>

@endsection

resources/views/calls/index_calls.blade.php
@extends('layout')
@section('content')

  <div class="container">
    <div class="d-flex flex-column mb-5">
      <h3>List calls</h3>
    </div>
    <div class="d-flex flex-column">
      <table class="table table-bordered">
        <thead>
        <tr>
          <th scope="col" class="text-center">ID</th>
          <th scope="col">Description</th>
          <th scope="col">User Name</th>
          <th scope="col">Status</th>
          <th scope="col">Created At</th>
          <th scope="col" class="text-center">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($calls as $call)
          <tr>
            <th scope="row" class="text-center">{{$call->id}}</th>
            <td>{{$call->description}}</td>
            <td>{{$call->user->name}}</td>
            <td>{{$call->status}}</td>
            <td>{{$call->created_at}}</td>
            <td class="text-center">
              {!! Form::open(['url'=>route('calls.destroy',['call'=>$call->id]), 'class'=>'form-horizontal','method' => 'POST']) !!}
              {{method_field('delete')}}
              {!! Form::button('Delete',['class'=>'btn btn-danger','type'=>'submit']) !!}
              {!! Form::close() !!}
              </a>
            </td>
          </tr>
        @endforeach
        </tbody>
      </table>
    </div>
    <div class="d-flex flex-column">
      {{ $calls->onEachSide(2)->links() }}
    </div>
  </div>
@endsection

resources/views/layout.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{env('APP_NAME')}} Test</title>

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://unpkg.com/ionicons@4.5.5/dist/ionicons.js"></script>
</head>
<body>
<div class="container">
  <div class="d-flex flex-column">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link active" href="{{route('home')}}">Users</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('calls.index')}}">Calls</a>
      </li>

    </ul>
  </div>
</div>
<div class="d-flex flex-column bd-highlight mb-3">

  <div class="d-flex justify-content-center mb-5 mt-5">
    <h1 class="">{{env('APP_NAME')}} Test</h1>
  </div>
  <div id="app">
    @yield('content')
  </div>
</div>
</div>

{{--<script src="{!! asset('js/app.js') !!}"></script>--}}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
</body>
</html>

resources/views/user_calls.blade.php
@extends('layout')
@section('content')

  <div class="container">
    <div class="d-flex flex-column mb-5 mt-5">
      <h3>User name is {{$user->name}}</h3>
    </div>
    <div class="d-flex flex-column">
      <table class="table table-bordered">
        <thead>
        <tr>
          <th scope="col" class="text-center">ID</th>
          <th scope="col">Description</th>
          <th scope="col">Status</th>
          <th scope="col">Created At</th>
          <th scope="col" class="text-center">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($calls as $call)
          <tr>
            <th scope="row" class="text-center">{{$call->id}}</th>
            <td>{{$call->description}}</td>
            <td>{{$call->status}}</td>
            <td>{{$call->created_at}}</td>
            <td class="text-center">
              {!! Form::open(['url'=>route('calls.destroy',['call'=>$call->id]), 'class'=>'form-horizontal','method' => 'POST']) !!}
              {{method_field('delete')}}
              {!! Form::button('Delete',['class'=>'btn btn-danger','type'=>'submit']) !!}
              {!! Form::close() !!}
              </a>
            </td>
          </tr>
        @endforeach
        </tbody>
      </table>
    </div>
    <div class="d-flex flex-column">
      {{ $calls->links() }}
    </div>
    <div class="d-flex flex-row">
      <a class="btn btn-primary" href="{{route('calls.create',['user_id' => $user->id])}}" role="button">Add new
        call</a>
    </div>

  </div>
@endsection

resources/views/users.blade.php
@extends('layout')
@section('content')
  <div class="container">
    <div class="d-flex flex-column mb-5">
      <h3>List users</h3>
    </div>
    <div class="d-flex flex-column">
        <table class="table table-bordered">
          <thead>
          <tr>
            <th scope="col" class="text-center">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Created At</th>
            <th scope="col" class="text-center">History calls</th>
          </tr>
          </thead>
          <tbody>
          @foreach($users as $user)
            <tr>
              <th scope="row" class="text-center">{{$user->id}}</th>
              <td>{{$user->name}}</td>
              <td>{{$user->email}}</td>
              <td>{{$user->created_at}}</td>
              <td class="text-center">
                <a href="{{ route('user.calls',['user' => $user->id]) }}">
                <ion-icon name="call"></ion-icon>
                </a>
              </td>
            </tr>
          @endforeach

          </tbody>
        </table>

    </div>
    <div class="d-flex flex-column">
      {{ $users->onEachSide(2)->links() }}
    </div>
  </div>

@endsection